version: '3'

networks:
  application:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
    - "8008:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - postres
    networks:
      - application
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - application
  postgres:
    image: postgres:14.2
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - application
  pgweb:
    image: sosedoff/pgweb
    container_name: ${APP_NAME}_pgweb
    restart: always
    ports: 
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - application